#!/usr/bin/env bash
# Startup script of the Airflow VM (infra/airflow_vm.tf). Runs on every boot
# (spot VMs stop and start), so every step is idempotent.
# Log: sudo journalctl -u google-startup-scripts
set -euo pipefail

md() { curl -fsS -H Metadata-Flavor:Google "http://metadata.google.internal/computeMetadata/v1/instance/$1"; }
attr() { md "attributes/$1"; }
root=/opt/uplift
dc() { docker compose -f "$root/airflow/docker-compose.yml" "$@"; }

image=$(attr airflow-image)
bucket=$(attr data-bucket)
mlflow_uri=$(attr mlflow-uri)
idle_minutes=$(attr idle-minutes)

# 1. Idle shutdown first, so the VM stops itself even if a later step fails.
cat >/usr/local/bin/uplift-idle-check <<'EOF'
#!/usr/bin/env bash
# Power off once no run of an unpaused DAG has been running or queued for
# IDLE_MINUTES and the VM has been up at least that long.
# ponytail: a run stuck in "running" keeps the VM up; the budget guard is the backstop.
set -uo pipefail
stamp=/var/lib/uplift-last-busy
limit=$((${IDLE_MINUTES:-30} * 60))
busy=$(docker compose -f /opt/uplift/airflow/docker-compose.yml exec -T postgres \
  psql -U airflow -tAc "select count(*) from dag_run r join dag d using (dag_id)
    where r.state in ('queued', 'running') and not d.is_paused" 2>/dev/null)
# A failed query counts as idle: with Postgres down no run can progress.
if [ "${busy:-0}" -gt 0 ] 2>/dev/null; then
  touch "$stamp"
  exit 0
fi
up=$(cut -d. -f1 /proc/uptime)
last=$(stat -c %Y "$stamp" 2>/dev/null || echo 0)
if [ "$up" -ge "$limit" ] && [ $(($(date +%s) - last)) -ge "$limit" ]; then
  logger -t uplift-idle "no DAG run for ${IDLE_MINUTES:-30} min, powering off"
  systemctl poweroff
fi
EOF
chmod 755 /usr/local/bin/uplift-idle-check
cat >/etc/systemd/system/uplift-idle.service <<EOF
[Unit]
Description=Power off the VM when Airflow is idle
[Service]
Type=oneshot
Environment=IDLE_MINUTES=$idle_minutes
ExecStart=/usr/local/bin/uplift-idle-check
EOF
cat >/etc/systemd/system/uplift-idle.timer <<'EOF'
[Unit]
Description=Check every 5 minutes whether Airflow is idle
[Timer]
OnBootSec=5min
OnUnitActiveSec=5min
[Install]
WantedBy=timers.target
EOF
systemctl daemon-reload
systemctl enable --now uplift-idle.timer

# 2. Docker Engine and the Compose plugin, from Docker's repository (Debian's
# own docker-compose is the old v1).
if ! docker compose version >/dev/null 2>&1; then
  install -d -m 0755 /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable" \
    >/etc/apt/sources.list.d/docker.list
  apt-get update -q
  DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    docker-ce docker-ce-cli containerd.io docker-compose-plugin
fi

# 3. Compose file and DAG from instance metadata; .env from Secret Manager with
# the VM-specific values forced.
mkdir -p "$root/airflow" "$root/dags" "$root/data/raw/x5"
attr compose-yaml >"$root/airflow/docker-compose.yml"
attr dag-py >"$root/dags/uplift_training_dag.py"
dotenv=$(gcloud secrets versions access latest --secret=uplift-airflow-env)
(
  umask 077
  {
    grep -vE '^(AIRFLOW_IMAGE|AIRFLOW_UID|UPLIFT_DATA_HOST_DIR|MLFLOW_TRACKING_URI|MLFLOW_TRACKING_TOKEN)=' <<<"$dotenv" || true
    echo "AIRFLOW_IMAGE=$image"
    echo "AIRFLOW_UID=50000"
    echo "UPLIFT_DATA_HOST_DIR=$root/data"
    echo "MLFLOW_TRACKING_URI=$mlflow_uri"
    # Empty: the train task mints identity tokens from the metadata server.
    echo "MLFLOW_TRACKING_TOKEN="
  } >"$root/airflow/.env.tmp"
)
mv "$root/airflow/.env.tmp" "$root/airflow/.env"

# 4. Raw data only; processed and features are regenerated by the DAG.
gcloud storage rsync "gs://$bucket/raw/x5" "$root/data/raw/x5" ||
  echo "no raw data in gs://$bucket/raw/x5 yet; upload it with scripts/fetch_x5.sh" >&2
chown -R 50000:0 "$root/data"

# 5. Pull and start. The access token lasts an hour, enough for the pull.
md service-accounts/default/token |
  python3 -c 'import json, sys; print(json.load(sys.stdin)["access_token"])' |
  docker login -u oauth2accesstoken --password-stdin "https://${image%%/*}"
dc pull --quiet || echo "pull failed, starting from cached images" >&2
dc up -d --no-build --remove-orphans
